import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "node:fs";
import path from "node:path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const pad2 = (value) => String(value).padStart(2, "0");

const formatBuildTime = (date) => {
  const yyyy = date.getFullYear();
  const mm = pad2(date.getMonth() + 1);
  const dd = pad2(date.getDate());
  const hh = pad2(date.getHours());
  const min = pad2(date.getMinutes());

  const offsetMin = -date.getTimezoneOffset();
  const sign = offsetMin >= 0 ? "+" : "-";
  const absOffset = Math.abs(offsetMin);
  const offH = pad2(Math.floor(absOffset / 60));
  const offM = pad2(absOffset % 60);

  return `${yyyy}-${mm}-${dd}T${hh}:${min} (UTC${sign}${offH}:${offM})`;
};

const buildTime = formatBuildTime(new Date());

const prod = process.argv[2] === "production";

const vaultPath = process.env.OBSIDIAN_VAULT_PATH ?? "C:\\Obsidian\\Dev";
const outDir = path.join(
  vaultPath,
  ".obsidian",
  "plugins",
  "obsidian-wasm-image"
);

if (!fs.existsSync(outDir)) {
  fs.mkdirSync(outDir, { recursive: true });
}

/**
 * @jsquash/webp 配下の .js/.mjs/.cjs を全部捕まえて、
 *  1) Emscripten の `function(Module = {})` を安全形へ
 *  2) *.wasm 参照を data:URL に強制（import.meta / import_meta 両対応）
 *    - 生成する data: は 'data:application/octet-stream;base64,...' にして
 *      ライブラリ内の isDataURI 判定に確実に引っかかるようにする
 *  3) `new URL(*, import.meta.url)`/`new URL(*, import_meta.url)` を**全部**置換
 */
const fixJsquash = {
  name: "fix-jsquash",
  setup(build) {
    // Windows のバックスラッシュにもマッチするように [/\\] を使用
    const filter = /(?:^|[/\\])node_modules[/\\]@jsquash[/\\].*\.(?:js|mjs|cjs)$/;

    build.onLoad({ filter }, async (args) => {
      let code = await fs.promises.readFile(args.path, "utf8");
      const dir = path.dirname(args.path);

      // (1) Emscripten のデフォルト引数を安全形へ
      code = code
        .replace(
          /function\s*\(\s*Module\s*=\s*\{\}\s*\)\s*\{/g,
          'function(Module){ Module = Module || {};'
        )
        .replace(
          /function\s*\(\s*Module\s*=\s*Module\s*\|\|\s*\{\}\s*\)\s*\{/g,
          'function(Module){ Module = Module || {};'
        );

      // (2) このファイルで参照している wasm 名を拾う（最初の *.wasm）
      const wasmRel =
        code.match(/["']([^"']*webp_enc[^"']*\.wasm)["']/)?.[1] ||
        code.match(/["']([^"']*\.wasm)["']/)?.[1];

      if (wasmRel) {
        const wasmAbs = path.join(dir, wasmRel);
        const wasmBin = await fs.promises.readFile(wasmAbs);
        const dataPrefix = "data:application/octet-stream;base64,";
        const dataUrl = `${dataPrefix}${wasmBin.toString("base64")}`;

        // (3-a) new URL(..., import.meta.url) → new URL("data:...", ) に強制
        //  import.meta でも import_meta でもヒットさせる
        code = code.replace(
          /new\s+URL\s*\(\s*[^,]+,\s*(?:import\.meta|import_meta)\.url\s*\)/g,
          `new URL("${dataUrl}")`
        );

        // (3-b) 念のため、 locateFile 分岐で素の "xxx.wasm" を代入している場合も潰す
        //   wasmBinaryFile = "webp_enc*.wasm";
        code = code.replace(
          /wasmBinaryFile\s*=\s*["'][^"']*\.wasm["']\s*;/g,
          `wasmBinaryFile = "${dataUrl}";`
        );

        console.log(`[inline] ${path.basename(args.path)} -> ${path.basename(wasmAbs)} (inlined)`);
      }

      return { contents: code, loader: "js" };
    });
  },
};

const copyStaticFiles = {
  name: "copy-static-files",
  setup(build) {
    build.onEnd(() => {
      try {
        fs.copyFileSync("manifest.json", path.join(outDir, "manifest.json"));

        // Concatenate CSS files: _variables.css + styles.css
        const cssDir = "src/styles";
        const cssFiles = ["_variables.css", "styles.css"];
        let cssContent = "";
        for (const file of cssFiles) {
          const filePath = path.join(cssDir, file);
          if (fs.existsSync(filePath)) {
            cssContent += fs.readFileSync(filePath, "utf8") + "\n";
          }
        }
        if (cssContent) {
          fs.writeFileSync(path.join(outDir, "styles.css"), cssContent);
        }

        console.log("Built to " + outDir);
      } catch (e) {
        console.error("Failed to copy static files:", e);
      }
    });
  },
};

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  define: {
    __BUILD_TIME__: JSON.stringify(buildTime),
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    ...builtins,
  ],
  format: "cjs",
  platform: "browser",
  target: "es2022",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: path.join(outDir, "main.js"),
  loader: { ".wasm": "dataurl", ".ts": "ts" },
  plugins: [fixJsquash, copyStaticFiles],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
